# Generated by Django 5.0.6 on 2024-07-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='cant_jugadores',
            field=models.CharField(max_length=50),
        ),
    ]
