# Generated by Django 5.0.6 on 2024-07-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_imagenusuario_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='consolas/'),
        ),
    ]
