# Generated by Django 5.0.6 on 2024-07-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0006_consolas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='consolas/'),
        ),
        migrations.AddField(
            model_name='libros',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='consolas/'),
        ),
        migrations.AddField(
            model_name='miniaturas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='consolas/'),
        ),
    ]
