# Generated by Django 5.0.6 on 2024-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_juegos_de_mesa_imagen_libros_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesproductos/'),
        ),
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesproductos/'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesproductos/'),
        ),
        migrations.AlterField(
            model_name='miniaturas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesproductos/'),
        ),
    ]
